set -o vi

export MT_EDITOR=nvim
export VISUAL=nvim

eval "$(starship init zsh)"

f() {
    fff "$@"
    cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
}

timeout 3s pfetch

# =======================================================
# MKTEX configuration

MKTEX_TEMPLATE_DIR="$HOME/.config/mktex_templates"

# =======================================================

resetcursor() {
  printf '\033]50;CursorShape=1\x7'
}
export PS1="$(resetcursor)$PS1"
