#! /bin/sh

pkill picom
picom --corner-radius 15 --experimental-backends &
nitrogen --restore &
~/.config/polybar/launch.sh
# sleep after 7 minutes
#xset s 420 10


pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap          20

bspc config top_padding         25
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiling

eww daemon
eww open right

# only add if nothing is there
#if test "$(mpc playlist | wc -l)" -eq 0 ; then
#  mpc ls | mpc add
#fi
