#!/usr/bin/env bash

export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
uim-xim &
export XMODIFIERS=@im=uim

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

dbus-update-activation-environment DISPLAY XAUTHORITY
exec bspwm
